package dev.prisonerofum.EGRINGOTTS.Account;

import dev.prisonerofum.EGRINGOTTS.Card;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import java.util.Date;


@Document(collection="Account") //to specify the collection name
@Data                           //take care of all getter and setter
@AllArgsConstructor             //constructor with all arguments
@NoArgsConstructor              //constructor with no arguments
public class Account<E> { //Account class with generic type E

    //hold data and all class

    @Id                         //to specify the primary key
    private ObjectId id;        //ObjectId that generated by mongoDB
    private String username;
    private String password;
    private Date DOB;
    private String email;
    private String phone;
    private String address;
    private String accountType;
//    private String accountStatus;

    @DocumentReference           //to specify the reference to another document
    private Card cards;





}
